version: '3'
services:
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app/:/app
