apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: flask-app
  template:
    metadata:
      labels:
        component: flask-app
    spec:
      containers:
        - name: flask-app
          image: bigjack213/food-app
          ports:
            containerPort: 5000
  